[build]
  command = "npm run build"
  publish = "dist/instant-brut/browser" # REMPLACE 'instant-brut' par le nom exact dans ton dossier dist

# ON SUPPRIME TOUTE LA SECTION [[plugins]] QUI CONTIENT @netlify/angular-runtime
